### ISSUE TITLE
built-in search

### ISSUE THREAD

**Issue by TomTasche** [opendocument-app/OpenDocument.core#115]
e.g. http://markjs.io

necessary for https://github.com/TomTasche/OpenDocument.ios/issues/17

Requirement for this task to be considered done:

- expose a global javascript method that takes a string as input and highlights all occurrences of that string in the current document
- expose two global javascript methods for jumping to the next / previous occurrence
- expose a global javascript method that clears all highlights

These javascript methods are fairly easy to call from the platform (i.e. Android and iOS). UI is implemented in the platforms, not in HTML.

**Comment by TomTasche** [comment]
I'd suggest to create a prototype implementation purely inside an output HTML file of OpenDocument.core. Afterwards someone else can change the C++ code so that it includes the necessary scripts, etc.

**Comment by marcelblanarik** [comment]
Please check it out here: https://github.com/marcelblanarik/js-keyword-highlighter

**Comment by TomTasche** [comment]
Draft implementation based on Marcel's prototype available here: https://github.com/opendocument-app/OpenDocument.core/tree/feature/search

Problem: calling search triggers our MutationObserver and generates an unnecessary diff.

**Comment by andiwand** [comment]
do you know if the diff is harmful?
