### ISSUE TITLE
modified ODTs have mime type of ZIP

### ISSUE THREAD

**Issue by TomTasche** [opendocument-app/OpenDocument.core#152]
I'm pretty sure we did some research on that already, but I'd like to keep it visible as a ticket. It's a mystery how this is possible at all...

**Comment by andiwand** [comment]
do you have sample data? (original file + output)

**Comment by TomTasche** [comment]
Yes! [testdata.zip](https://github.com/opendocument-app/OpenDocument.core/files/4476552/testdata.zip)

**Comment by andiwand** [comment]
the only difference i see so far is the order of the files in the zip. not sure if it is about that. further investigation needed.

**Comment by andiwand** [comment]
yes it is about the order in the zip
```
$ file *
testedit2.odt: OpenDocument Text
testedit.odt:  Zip archive data, at least v?[0x314] to extract
test.odt:      OpenDocument Text
```
`testedit2.odt` only contains the `mimetype` file and still says that it is an `odt`.

i think i read somewhere that an `odt` could only have a `content.xml` and would still be vaild. i think it was on wikipedia but i cannot find it right now.

i think this is a limitation of linux `file` and not of our code, but i can put the `mimetype` file first if you want.

**Comment by TomTasche** [comment]
nice! problem is that we rely on the file command a lot on Android. would be great if we could change that!

**Comment by andiwand** [comment]
yeah i can do that but for me it sounds like we should not rely on `file` because of that.

**Comment by TomTasche** [comment]
what else would you suggest to determine the type of any file?

**Comment by andiwand** [comment]
first using our api and if it is unknown use `file`

**Comment by TomTasche** [comment]
good idea, but still need a separate solution for encrypted OOXML and DOC

**Comment by andiwand** [comment]
```
andreas@andreas-dev:~/workspace/OpenDocument.test$ file doc/encrypted\$password\$.doc docx/encrypted\$password\$.docx 
doc/encrypted$password$.doc:   Composite Document File V2 Document, Little Endian, Os: Windows, Version 1.0, Code page: -535, Revision Number: 0, Create Time/Date: Sun Jan 19 09:15:39 2020
docx/encrypted$password$.docx: CDFV2 Encrypted
```
