### ISSUE TITLE
xlsx crashing

### ISSUE THREAD

**Issue by andiwand** [opendocument-app/OpenDocument.core#212]
see `xlsx/Ordnerruecken.xlsx`

**Comment by andiwand** [comment]
@TomTasche did this file crash or was it not correctly displayed? for me it is working but i didn't check the formatting.

**Comment by TomTasche** [comment]
I don't have a device handy to test, but the customer said it crashes whenever he tries to open the second sheet of that file! Could be related to the way I'm handling multi-sheet files? Will debug on my side and add more details.

**Comment by TomTasche** [comment]
really strange bug, looks like a lifecycle issue? I sometimes manage to avoid the crash for this document. sometimes it only crashes after clicking on the first page again after switching to the second... would require some live iOS debugging together!

<img width="1440" alt="Screenshot 2020-10-19 at 20 51 09" src="https://user-images.githubusercontent.com/128734/96498820-d973ee00-124c-11eb-9a99-7716350cd9f1.png">

**Comment by TomTasche** [comment]
With fully visible stacktrace.

<img width="1440" alt="Screenshot 2020-10-19 at 20 53 16" src="https://user-images.githubusercontent.com/128734/96499016-1e982000-124d-11eb-981b-597d96530cb7.png">

**Comment by andiwand** [comment]
do you have a screenshot / line number for function call `1` in the stack trace?

**Comment by TomTasche** [comment]
<img width="1440" alt="Screenshot 2020-10-19 at 21 24 23" src="https://user-images.githubusercontent.com/128734/96501989-78024e00-1251-11eb-927c-71e4b1ccabf4.png">

**Comment by andiwand** [comment]
yeah lets try to debug this together on the platform. i cannot reproduce it
