### ISSUE TITLE
restrict editing

### ISSUE THREAD

**Issue by andiwand** [opendocument-app/OpenDocument.core#284]
currently the UI suggests that we have more editing capabilities than we actually do have which is confusing and frustrating for the user. we should limit the UI and match the backend in this regards.

**editing capability ladder**
- modify words and sentences
- add/remove line breaks
- add/remove paragraphs
- add/remove any other kind of content

the HTML must contain the editing capabilities of the underlying document and JS has to verify that the document is not edited in a way that cannot be included after saving the document back to the original format.

a communication channel to the platform should inform the user when he is trying to edit a document in a way that is not supported. the user should be educated why this is the case and what else he is able to do and that this might be improved in the near future.

**references**
- https://stackoverflow.com/questions/425274/prevent-line-paragraph-breaks-in-contenteditable
- https://stackoverflow.com/questions/51775344/disabling-pasting-completely-in-contenteditable-divs

**Comment by TomTasche** [comment]
Is there a way to "block" or undo unsupported operations, or is the only thing we can do to tell the user that "it's not going to work"?

**Comment by andiwand** [comment]
@TomTasche I hope for a solution that prevents the user from editing the document in a way we don't support. I will investigate out options there first. if possible I would still show a short message that we canceled the last edit

otherwise we can fall back to a message and then refuse to save the documents with the given edits with a descriptive message
