### ISSUE TITLE
tests succeed even if files do not exist

### ISSUE THREAD

**Issue by TomTasche** [opendocument-app/OpenDocument.core#50]
running OpenDocumentBackTranslationTest on my computer does not fail, although the file /home/andreas/Desktop/odr/megatest.odt does not exist

**Comment by andiwand** [comment]
i don't use unit tests properly here. i guess the full translation top-bottom is more like an integration test and we do that in the ci. i would just drop the none unit tests.

**Comment by TomTasche** [comment]
this is done with your latest travis changes, no? @andiwand

**Comment by andiwand** [comment]
since i just removed the unit tests, yes. 😄
